@clientUrl = http://localhost:8000
@serverUrl = http://localhost:8080

# @accessToken = {{login.response.cookie.accessToken}}
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidHdvX2ZhY3Rvcl9hY3RpdmF0ZWQiOmZhbHNlLCJpYXQiOjE2Njk3NTg3MjAsImV4cCI6MTY2OTc2MjMyMH0.q1Aojo7ocZq6EwcmpacfqVg4vsKqy_M_x2gkFy_IMT0


### Get current user info
Get {{serverUrl}}/users/ HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Post new username
Post {{serverUrl}}/setting/username HTTP/1.1
content-type: application/json
Cookie: accessToken = {{accessToken}}

# body
{
    "username":"hohdss"
}



### Get all chatrooms
Get {{serverUrl}}/chatroom/ HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Get a chatroom
Get {{serverUrl}}/chatroom/2/ HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Get all memebers from a chatroom
Get {{serverUrl}}/chatroom/2/members/ HTTP/1.1
Cookie: accessToken = {{accessToken}}
