@clientUrl = http://localhost:8000
@serverUrl = http://localhost:8080

# @accessToken = {{login.response.cookie.accessToken}}
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInR3b19mYWN0b3JfYWN0aXZhdGVkIjpmYWxzZSwiaWF0IjoxNjY5NzcyMzAxLCJleHAiOjE2Njk3NzU5MDF9.8SGwTgSRF6cImtT7k6HDFjC6VhKABctlxHXJrVIx6eo


### Get current user info
Get {{serverUrl}}/users/ HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Get all users info
Get {{serverUrl}}/users/all HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Post new username
Post {{serverUrl}}/setting/username HTTP/1.1
content-type: application/json
Cookie: accessToken = {{accessToken}}

# body
{
    "username":"hohdss"
}



### Get all chatrooms
Get {{serverUrl}}/chatroom/ HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Get a chatroom
Get {{serverUrl}}/chatroom/2/ HTTP/1.1
Cookie: accessToken = {{accessToken}}

### Get all memebers from a chatroom
Get {{serverUrl}}/chatroom/25/members/ HTTP/1.1
Cookie: accessToken = {{accessToken}}
